/* tslint:disable */
import { InstallationLite, Organization, Repository } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SecretScanningAlertCreatedEvent {
  action: 'created';
  /**
   * The secret scanning alert involved in the event.
   */
  alert: {
    number: number;
    secret_type: string;
    resolution: null;
    resolved_by: null;
    resolved_at: null;
  };
  repository: Repository;
  organization?: Organization;
  installation?: InstallationLite;
}
