/* tslint:disable */
import {
  Committer,
  InstallationLite,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StatusEvent {
  /**
   * The unique identifier of the status.
   */
  id: number;
  /**
   * The Commit SHA.
   */
  sha: string;
  name: string;
  avatar_url?: string | null;
  /**
   * The optional link added to the status.
   */
  target_url: string | null;
  context: string;
  /**
   * The optional human-readable description added to the status.
   */
  description: string | null;
  /**
   * The new state. Can be `pending`, `success`, `failure`, or `error`.
   */
  state: 'pending' | 'success' | 'failure' | 'error';
  commit: {
    sha: string;
    node_id: string;
    commit: {
      author: Committer & {
        date: string;
      };
      committer: Committer & {
        date: string;
      };
      message: string;
      tree: {
        sha: string;
        url: string;
      };
      url: string;
      comment_count: number;
      verification: {
        verified: boolean;
        reason:
          | 'expired_key'
          | 'not_signing_key'
          | 'gpgverify_error'
          | 'gpgverify_unavailable'
          | 'unsigned'
          | 'unknown_signature_type'
          | 'no_user'
          | 'unverified_email'
          | 'bad_email'
          | 'unknown_key'
          | 'malformed_signature'
          | 'invalid'
          | 'valid';
        signature: string | null;
        payload: string | null;
      };
    };
    url: string;
    html_url: string;
    comments_url: string;
    author: User | null;
    committer: User | null;
    parents: {
      sha: string;
      url: string;
      html_url: string;
    }[];
  };
  /**
   * An array of branch objects containing the status' SHA. Each branch contains the given SHA, but the SHA may or may not be the head of the branch. The array includes a maximum of 10 branches.
   */
  branches: {
    name: string;
    commit: {
      sha: string;
      url: string;
    };
    protected: boolean;
  }[];
  created_at: string;
  updated_at: string;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
