service: gh-webhooks-schema-checker

useDotenv: true
frameworkVersion: '2'
unresolvedVariablesNotificationMode: error

plugins:
  - serverless-plugin-scripts
  - serverless-azure-functions

provider:
  name: azure
  region: Australia East
  runtime: nodejs12
  stage: dev

  # These environment vars are installed into **all** functions in the service
  environment:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    GH_WEBHOOK_SECRET: ${env:GH_WEBHOOK_SECRET}

custom:
  outDir: ${file(./tsconfig.build.json):compilerOptions.outDir}
  prepareForPacking: &prepareForPacking |
    npm run --silent build
  scripts:
    hooks:
      'before:package:createDeploymentArtifacts': *prepareForPacking
      'before:deploy:function:packageFunction': *prepareForPacking

package:
  include:
    - ${self:custom.outDir}/**/*
    - package.json
  exclude:
    - '**/*'
    - '!node_modules/**'
    - '!**/function.json'
    - '**/*.d.ts'
    - '**/*.md'

functions:
  compareWebhookPayloadToSchema:
    handler: lib/index.handler
    events:
      - http: true
        authLevel: anonymous
        methods:
          - post
        route: github
      - http: true
        direction: out
        name: '$return'
