/* tslint:disable */
import { Installation, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateEvent {
  ref: string;
  ref_type: string;
  master_branch: string;
  description: string | null;
  pusher_type: string;
  repository: Repository;
  sender: User;
  installation?: Installation | null;
  organization?: Organization | null;
}
