/* tslint:disable */
import { Installation, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommitCommentCreatedEvent {
  action: 'created';
  comment: {
    url: string;
    html_url: string;
    id: number;
    node_id: string;
    user: {
      login: string;
      id: number;
      node_id: string;
      avatar_url: string;
      gravatar_id: string;
      url: string;
      html_url: string;
      followers_url: string;
      following_url: string;
      gists_url: string;
      starred_url: string;
      subscriptions_url: string;
      organizations_url: string;
      repos_url: string;
      events_url: string;
      received_events_url: string;
      type: string;
      site_admin: boolean;
    };
    position: null;
    line: null;
    path: null;
    commit_id: string;
    created_at: string;
    updated_at: string;
    author_association: string;
    body: string;
  };
  repository: Repository;
  sender: User;
  installation?: Installation;
  organization?: Organization;
}
