/* tslint:disable */
import { InstallationLite, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RepositoryPublicizedEvent {
  action: 'publicized';
  repository: Repository & {
    /**
     * Whether the repository is private or public.
     */
    private: false;
  };
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
