/* tslint:disable */
import {
  InstallationLite,
  Label,
  Organization,
  PullRequest,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PullRequestLabeledEvent {
  action: 'labeled';
  /**
   * The pull request number.
   */
  number: number;
  pull_request: PullRequest;
  label: Label;
  repository: Repository;
  installation?: InstallationLite;
  organization?: Organization;
  sender: User;
}
