/* tslint:disable */
import {
  InstallationLite,
  Milestone,
  Organization,
  PullRequest,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PullRequestMilestonedEvent {
  action: 'milestoned';
  /**
   * The pull request number.
   */
  number: number;
  pull_request: PullRequest & {
    milestone: Milestone;
  };
  milestone: Milestone;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
