/* tslint:disable */
import {
  InstallationLite,
  Organization,
  PullRequest,
  Repository,
  Team,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PullRequestReviewRequestRemovedEvent =
  | {
      action: 'review_request_removed';
      /**
       * The pull request number.
       */
      number: number;
      pull_request: PullRequest;
      requested_reviewer: User;
      repository: Repository;
      installation?: InstallationLite;
      organization?: Organization;
      sender: User;
    }
  | {
      action: 'review_request_removed';
      /**
       * The pull request number.
       */
      number: number;
      pull_request: PullRequest;
      requested_team: Team;
      repository: Repository;
      installation?: InstallationLite;
      organization?: Organization;
      sender: User;
    };
