/* tslint:disable */
import {
  InstallationLite,
  Organization,
  ProjectsV2Item,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsV2ItemConvertedEvent {
  changes: {
    content_type: {
      from: 'DraftIssue';
      to: 'Issue';
    };
  };
  action: 'converted';
  projects_v2_item: ProjectsV2Item & {
    content_type: 'Issue';
  };
  sender: User;
  organization?: Organization;
  installation?: InstallationLite;
}
