/* tslint:disable */
import {
  InstallationLite,
  Organization,
  ProjectsV2Item,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectsV2ItemReorderedEvent {
  changes: {
    previous_projects_v2_item_node_id: {
      from: string;
      to: string | null;
    };
  };
  action: 'reordered';
  projects_v2_item: ProjectsV2Item;
  sender: User;
  organization?: Organization;
  installation?: InstallationLite;
}
