/* tslint:disable */
import {
  Discussion,
  InstallationLite,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DiscussionTransferredEvent {
  changes: {
    new_discussion: Discussion;
    new_repository: Repository;
  };
  action: 'transferred';
  discussion: Discussion;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
