/* tslint:disable */
import { InstallationLite, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A wiki page is created or updated.
 */
export interface GollumEvent {
  /**
   * The pages that were updated.
   */
  pages: {
    /**
     * The name of the page.
     */
    page_name: string;
    /**
     * The current page title.
     */
    title: string;
    summary: null;
    /**
     * The action that was performed on the page. Can be `created` or `edited`.
     */
    action: 'created' | 'edited';
    /**
     * The latest commit SHA of the page.
     */
    sha: string;
    /**
     * Points to the HTML wiki page.
     */
    html_url: string;
  }[];
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
