/* tslint:disable */
import { Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StarCreatedEvent {
  action: 'created';
  starred_at: null | string;
  repository: Repository;
  sender: User;
  organization?: Organization | null;
}
