/* tslint:disable */
import { InstallationLite, Membership, Organization, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrganizationMemberRemovedEvent {
  action: 'member_removed';
  membership: Membership;
  sender: User;
  installation?: InstallationLite;
  organization: Organization;
}
