/* tslint:disable */
import { Installation, Organization, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrganizationMemberInvitedEvent {
  action: 'member_invited';
  invitation: {
    [k: string]: unknown;
  };
  sender: User;
  installation?: Installation;
  organization: Organization;
}
