/* tslint:disable */
import { InstallationLite, Organization, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrganizationRenamedEvent {
  changes: {
    login: {
      from: string;
    };
  };
  action: 'renamed';
  sender: User;
  installation?: InstallationLite;
  organization: Organization;
}
