/* tslint:disable */
import { User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SponsorshipCancelledEvent {
  action: 'cancelled';
  sponsorship: {
    node_id: string;
    created_at: string;
    sponsorable: User;
    sponsor: User;
    privacy_level: string;
    tier: {
      node_id: string;
      created_at: string;
      description: string;
      monthly_price_in_cents: number;
      monthly_price_in_dollars: number;
      name: string;
    };
  };
  sender: User;
}
