/* tslint:disable */
import { Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TeamDeletedEvent {
  action: 'deleted';
  team: {
    name: string;
    id: number;
    node_id: string;
    slug: string;
    description: string | null;
    privacy: string;
    url: string;
    html_url: string;
    members_url: string;
    repositories_url: string;
    permission: string;
  };
  repository?: Repository;
  sender: User;
  organization: Organization;
}
