/* tslint:disable */
import { Organization, Repository, Team, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface TeamEditedEvent {
  action: 'edited';
  changes: {
    description?: {
      from: string;
    };
    name?: {
      from: string;
    };
    privacy?: {
      from: string;
    };
    repository?: {
      permissions: {
        from: {
          admin?: boolean;
          pull?: boolean;
          push?: boolean;
        };
      };
    };
  };
  team: Team;
  repository?: Repository;
  sender: User;
  organization: Organization;
}
