export * from './branch_protection_rule';
export * from './check_run';
export * from './check_suite';
export * from './code_scanning_alert';
export * from './commit_comment';
export * from './common';
export * from './create';
export * from './delete';
export * from './deploy_key';
export * from './deployment';
export * from './deployment_status';
export * from './discussion';
export * from './discussion_comment';
export * from './fork';
export * from './github_app_authorization';
export * from './gollum';
export * from './installation';
export * from './installation_repositories';
export * from './issue_comment';
export * from './issues';
export * from './label';
export * from './marketplace_purchase';
export * from './member';
export * from './membership';
export * from './merge_group';
export * from './meta';
export * from './milestone';
export * from './org_block';
export * from './organization';
export * from './package';
export * from './page_build';
export * from './ping';
export * from './project';
export * from './project_card';
export * from './project_column';
export * from './projects_v2_item';
export * from './public';
export * from './pull_request';
export * from './pull_request_review';
export * from './pull_request_review_comment';
export * from './pull_request_review_thread';
export * from './push';
export * from './release';
export * from './repository';
export * from './repository_dispatch';
export * from './repository_import';
export * from './repository_vulnerability_alert';
export * from './secret_scanning_alert';
export * from './security_advisory';
export * from './sponsorship';
export * from './star';
export * from './status';
export * from './team';
export * from './team_add';
export * from './watch';
export * from './workflow_dispatch';
export * from './workflow_job';
export * from './workflow_run';

import { BranchProtectionRuleEvent } from './branch_protection_rule';
import { CheckRunEvent } from './check_run';
import { CheckSuiteEvent } from './check_suite';
import { CodeScanningAlertEvent } from './code_scanning_alert';
import { CommitCommentEvent } from './commit_comment';
import { CreateEvent } from './create';
import { DeleteEvent } from './delete';
import { DeployKeyEvent } from './deploy_key';
import { DeploymentEvent } from './deployment';
import { DeploymentStatusEvent } from './deployment_status';
import { DiscussionEvent } from './discussion';
import { DiscussionCommentEvent } from './discussion_comment';
import { ForkEvent } from './fork';
import { GithubAppAuthorizationEvent } from './github_app_authorization';
import { GollumEvent } from './gollum';
import { InstallationEvent } from './installation';
import { InstallationRepositoriesEvent } from './installation_repositories';
import { IssueCommentEvent } from './issue_comment';
import { IssuesEvent } from './issues';
import { LabelEvent } from './label';
import { MarketplacePurchaseEvent } from './marketplace_purchase';
import { MemberEvent } from './member';
import { MembershipEvent } from './membership';
import { MergeGroupEvent } from './merge_group';
import { MetaEvent } from './meta';
import { MilestoneEvent } from './milestone';
import { OrgBlockEvent } from './org_block';
import { OrganizationEvent } from './organization';
import { PackageEvent } from './package';
import { PageBuildEvent } from './page_build';
import { PingEvent } from './ping';
import { ProjectEvent } from './project';
import { ProjectCardEvent } from './project_card';
import { ProjectColumnEvent } from './project_column';
import { ProjectsV2ItemEvent } from './projects_v2_item';
import { PublicEvent } from './public';
import { PullRequestEvent } from './pull_request';
import { PullRequestReviewEvent } from './pull_request_review';
import { PullRequestReviewCommentEvent } from './pull_request_review_comment';
import { PullRequestReviewThreadEvent } from './pull_request_review_thread';
import { PushEvent } from './push';
import { ReleaseEvent } from './release';
import { RepositoryEvent } from './repository';
import { RepositoryDispatchEvent } from './repository_dispatch';
import { RepositoryImportEvent } from './repository_import';
import { RepositoryVulnerabilityAlertEvent } from './repository_vulnerability_alert';
import { SecretScanningAlertEvent } from './secret_scanning_alert';
import { SecurityAdvisoryEvent } from './security_advisory';
import { SponsorshipEvent } from './sponsorship';
import { StarEvent } from './star';
import { StatusEvent } from './status';
import { TeamEvent } from './team';
import { TeamAddEvent } from './team_add';
import { WatchEvent } from './watch';
import { WorkflowDispatchEvent } from './workflow_dispatch';
import { WorkflowJobEvent } from './workflow_job';
import { WorkflowRunEvent } from './workflow_run';

export interface EventPayloadMap {
  branch_protection_rule: BranchProtectionRuleEvent;
  check_run: CheckRunEvent;
  check_suite: CheckSuiteEvent;
  code_scanning_alert: CodeScanningAlertEvent;
  commit_comment: CommitCommentEvent;
  create: CreateEvent;
  delete: DeleteEvent;
  deploy_key: DeployKeyEvent;
  deployment: DeploymentEvent;
  deployment_status: DeploymentStatusEvent;
  discussion: DiscussionEvent;
  discussion_comment: DiscussionCommentEvent;
  fork: ForkEvent;
  github_app_authorization: GithubAppAuthorizationEvent;
  gollum: GollumEvent;
  installation: InstallationEvent;
  installation_repositories: InstallationRepositoriesEvent;
  issue_comment: IssueCommentEvent;
  issues: IssuesEvent;
  label: LabelEvent;
  marketplace_purchase: MarketplacePurchaseEvent;
  member: MemberEvent;
  membership: MembershipEvent;
  merge_group: MergeGroupEvent;
  meta: MetaEvent;
  milestone: MilestoneEvent;
  org_block: OrgBlockEvent;
  organization: OrganizationEvent;
  package: PackageEvent;
  page_build: PageBuildEvent;
  ping: PingEvent;
  project: ProjectEvent;
  project_card: ProjectCardEvent;
  project_column: ProjectColumnEvent;
  projects_v2_item: ProjectsV2ItemEvent;
  public: PublicEvent;
  pull_request: PullRequestEvent;
  pull_request_review: PullRequestReviewEvent;
  pull_request_review_comment: PullRequestReviewCommentEvent;
  pull_request_review_thread: PullRequestReviewThreadEvent;
  push: PushEvent;
  release: ReleaseEvent;
  repository: RepositoryEvent;
  repository_dispatch: RepositoryDispatchEvent;
  repository_import: RepositoryImportEvent;
  repository_vulnerability_alert: RepositoryVulnerabilityAlertEvent;
  secret_scanning_alert: SecretScanningAlertEvent;
  security_advisory: SecurityAdvisoryEvent;
  sponsorship: SponsorshipEvent;
  star: StarEvent;
  status: StatusEvent;
  team: TeamEvent;
  team_add: TeamAddEvent;
  watch: WatchEvent;
  workflow_dispatch: WorkflowDispatchEvent;
  workflow_job: WorkflowJobEvent;
  workflow_run: WorkflowRunEvent;
}
