/* tslint:disable */
import {
  InstallationLite,
  Organization,
  Release,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReleaseEditedEvent {
  action: 'edited';
  changes: {
    body?: {
      /**
       * The previous version of the body if the action was `edited`.
       */
      from: string;
    };
    name?: {
      /**
       * The previous version of the name if the action was `edited`.
       */
      from: string;
    };
  };
  release: Release;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
