/* tslint:disable */
import {
  InstallationLite,
  Organization,
  ReleaseAsset,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReleaseEditedEvent {
  action: 'edited';
  changes: {
    body?: {
      from: string;
    };
    name?: {
      from: string;
    };
  };
  release: {
    url: string;
    assets_url: string;
    upload_url: string;
    html_url: string;
    id: number;
    node_id: string;
    /**
     * The name of the tag.
     */
    tag_name: string;
    /**
     * Specifies the commitish value that determines where the Git tag is created from.
     */
    target_commitish: string;
    name: null;
    /**
     * true to create a draft (unpublished) release, false to create a published one.
     */
    draft: boolean;
    author: User;
    /**
     * Whether the release is identified as a prerelease or a full release.
     */
    prerelease: boolean;
    created_at: string | null;
    published_at: string | null;
    assets: ReleaseAsset[];
    tarball_url: string | null;
    zipball_url: string | null;
    body: string | null;
  };
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
