/* tslint:disable */
import { Asset, Installation, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ReleasePrereleasedEvent {
  action: 'prereleased';
  release: {
    url: string;
    assets_url: string;
    upload_url: string;
    html_url: string;
    id: number;
    node_id: string;
    tag_name: string;
    target_commitish: string;
    name: null;
    draft: boolean;
    author: User;
    prerelease: true;
    created_at: string;
    published_at: string;
    assets: Asset[];
    tarball_url: string;
    zipball_url: string;
    body: string | null;
  };
  repository: Repository;
  sender: User;
  installation?: Installation;
  organization?: Organization;
}
