/* tslint:disable */
import {
  BranchProtectionRule,
  InstallationLite,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Activity related to a branch protection rule. For more information, see "[About branch protection rules](https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#about-branch-protection-rules)."
 */
export interface BranchProtectionRuleDeletedEvent {
  action: 'deleted';
  rule: BranchProtectionRule;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
