/* tslint:disable */
import { Installation, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectCardEditedEvent {
  action: 'edited';
  project_card: {
    url: string;
    project_url: string;
    column_url: string;
    column_id: number;
    id: number;
    node_id: string;
    note: string;
    archived: boolean;
    creator: User;
    created_at: string;
    updated_at: string;
    content_url: string;
  };
  repository: Repository;
  sender: User;
  organization?: Organization;
  installation?: Installation;
}
