/* tslint:disable */
import {
  InstallationLite,
  Organization,
  ProjectCard,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectCardMovedEvent {
  action: 'moved';
  changes: {
    column_id: {
      from: number;
    };
  };
  project_card: ProjectCard & {
    after_id: number | null;
  };
  repository: Repository;
  sender: User;
  organization?: Organization;
  installation?: InstallationLite;
}
