/* tslint:disable */
import {
  App,
  CheckRunPullRequest,
  InstallationLite,
  Organization,
  Repository,
  SimpleCommit,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CheckSuiteCompletedEvent {
  action: 'completed';
  check_suite: {
    id: number;
    node_id: string;
    head_branch: string | null;
    /**
     * The SHA of the head commit that is being checked.
     */
    head_sha: string;
    status: 'requested' | 'in_progress' | 'completed' | 'queued' | null;
    conclusion:
      | 'success'
      | 'failure'
      | 'neutral'
      | 'cancelled'
      | 'timed_out'
      | 'action_required'
      | 'stale'
      | null;
    url: string;
    before: string;
    after: string;
    pull_requests: CheckRunPullRequest[];
    app: App;
    created_at: string;
    updated_at: string;
    latest_check_runs_count: number;
    check_runs_url: string;
    head_commit: SimpleCommit;
  };
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
