/* tslint:disable */
import { Installation, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CheckSuiteCompletedEvent {
  action: 'completed';
  check_suite: {
    id: number;
    node_id: string;
    head_branch: string;
    head_sha: string;
    status: null | ('requested' | 'in_progress' | 'completed' | 'queued');
    conclusion:
      | null
      | (
          | 'success'
          | 'failure'
          | 'neutral'
          | 'cancelled'
          | 'timed_out'
          | 'action_required'
          | 'stale'
        );
    url: string;
    before: string;
    after: string;
    pull_requests: {
      url: string;
      id: number;
      number: number;
      head: {
        ref: string;
        sha: string;
        repo: {
          id: number;
          url: string;
          name: string;
        };
      };
      base: {
        ref: string;
        sha: string;
        repo: {
          id: number;
          url: string;
          name: string;
        };
      };
    }[];
    app: {
      id: number;
      node_id: string;
      owner: User;
      name: string;
      description: string;
      external_url: string;
      html_url: string;
      created_at: string;
      updated_at: string;
      permissions: {
        administration: string;
        checks: string;
        contents: string;
        deployments: string;
        issues: string;
        members: string;
        metadata: string;
        organization_administration: string;
        organization_hooks: string;
        organization_plan: string;
        organization_projects: string;
        organization_user_blocking: string;
        pages: string;
        pull_requests: string;
        repository_hooks: string;
        repository_projects: string;
        statuses: string;
        team_discussions: string;
        vulnerability_alerts: string;
      };
      events: {
        [k: string]: unknown;
      }[];
    };
    created_at: string;
    updated_at: string;
    latest_check_runs_count: number;
    check_runs_url: string;
    head_commit: {
      id: string;
      tree_id: string;
      message: string;
      timestamp: string;
      author: {
        name: string;
        email: string;
      };
      committer: {
        name: string;
        email: string;
      };
    };
  };
  repository: Repository;
  sender: User;
  installation?: Installation;
  organization?: Organization;
}
