/* tslint:disable */
import { Installation, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CheckSuiteRequestedEvent {
  action: 'requested';
  check_suite: {
    id: number;
    node_id: string;
    head_branch: string | null;
    head_sha: string;
    status: null | ('requested' | 'in_progress' | 'completed' | 'queued');
    conclusion:
      | null
      | (
          | 'success'
          | 'failure'
          | 'neutral'
          | 'cancelled'
          | 'timed_out'
          | 'action_required'
          | 'stale'
        );
    url: string;
    before: string;
    after: string;
    pull_requests: {
      url: string;
      id: number;
      number: number;
      head: {
        ref: string;
        sha: string;
        repo: {
          id: number;
          url: string;
          name: string;
        };
      };
      base: {
        ref: string;
        sha: string;
        repo: {
          id: number;
          url: string;
          name: string;
        };
      };
    }[];
    app: {
      id: number;
      slug?: string;
      node_id: string;
      owner: User;
      name: string;
      description: string;
      external_url: string;
      html_url: string;
      created_at: string;
      updated_at: string;
      permissions: {
        administration: 'read' | 'write';
        actions?: 'read' | 'write';
        checks: 'read' | 'write';
        contents: 'read' | 'write';
        deployments: 'read' | 'write';
        issues: 'read' | 'write';
        members: 'read' | 'write';
        metadata: 'read' | 'write';
        organization_administration: 'read' | 'write';
        organization_hooks: 'read' | 'write';
        organization_plan: 'read' | 'write';
        organization_projects: 'read' | 'write';
        organization_user_blocking: 'read' | 'write';
        pages: 'read' | 'write';
        pull_requests: 'read' | 'write';
        repository_hooks: 'read' | 'write';
        repository_projects: 'read' | 'write';
        statuses: 'read' | 'write';
        team_discussions: 'read' | 'write';
        vulnerability_alerts: 'read' | 'write';
      };
      events: {
        [k: string]: unknown;
      }[];
    };
    created_at: string;
    updated_at: string;
    latest_check_runs_count: number;
    check_runs_url: string;
    head_commit: {
      id: string;
      tree_id: string;
      message: string;
      timestamp: string;
      author: {
        name: string;
        email: string;
      };
      committer: {
        name: string;
        email: string;
      };
    };
  };
  repository: Repository;
  sender: User;
  installation?: Installation;
  organization?: Organization;
}
