/* tslint:disable */
import {
  App,
  Committer,
  Installation,
  Organization,
  RepoRef,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CheckSuiteRerequestedEvent {
  action: 'rerequested';
  check_suite: {
    id: number;
    node_id: string;
    head_branch: string | null;
    head_sha: string;
    status: 'requested' | 'in_progress' | 'completed' | 'queued' | null;
    conclusion:
      | 'success'
      | 'failure'
      | 'neutral'
      | 'cancelled'
      | 'timed_out'
      | 'action_required'
      | 'stale'
      | null;
    url: string;
    before: string;
    after: string;
    pull_requests: {
      url: string;
      id: number;
      number: number;
      head: {
        ref: string;
        sha: string;
        repo: RepoRef;
      };
      base: {
        ref: string;
        sha: string;
        repo: RepoRef;
      };
    }[];
    app: App;
    created_at: string;
    updated_at: string;
    latest_check_runs_count: number;
    check_runs_url: string;
    head_commit: {
      id: string;
      tree_id: string;
      message: string;
      timestamp: string;
      author: Committer;
      committer: Committer;
    };
  };
  repository: Repository;
  sender: User;
  installation?: Installation;
  organization?: Organization;
}
