/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AlertInstance {
  /**
   * The full Git reference, formatted as `refs/heads/<branch name>`.
   */
  ref: string;
  /**
   * Identifies the configuration under which the analysis was executed. For example, in GitHub Actions this includes the workflow filename and job name.
   */
  analysis_key: string;
  /**
   * Identifies the variable values associated with the environment in which the analysis that generated this alert instance was performed, such as the language that was analyzed.
   */
  environment: string;
  /**
   * State of a code scanning alert.
   */
  state: 'open' | 'dismissed' | 'fixed';
  commit_sha?: string;
  message?: {
    text?: string;
  };
  location?: {
    path?: string;
    start_line?: number;
    end_line?: number;
    start_column?: number;
    end_column?: number;
  };
  classifications?: string[];
}
