/* tslint:disable */
import { User } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface App {
  id: number;
  slug?: string;
  node_id: string;
  owner: User;
  name: string;
  description: string | null;
  external_url: string;
  html_url: string;
  created_at: string;
  updated_at: string;
  permissions?: {
    administration?: 'read' | 'write';
    actions?: 'read' | 'write';
    checks?: 'read' | 'write';
    contents?: 'read' | 'write';
    deployments?: 'read' | 'write';
    issues?: 'read' | 'write';
    members?: 'read' | 'write';
    metadata?: 'read' | 'write';
    organization_administration?: 'read' | 'write';
    organization_hooks?: 'read' | 'write';
    organization_plan?: 'read' | 'write';
    organization_projects?: 'read' | 'write';
    organization_user_blocking?: 'read' | 'write';
    pages?: 'read' | 'write';
    packages?: 'read' | 'write';
    pull_requests?: 'read' | 'write';
    repository_hooks?: 'read' | 'write';
    repository_projects?: 'read' | 'write';
    statuses?: 'read' | 'write';
    team_discussions?: 'read' | 'write';
    vulnerability_alerts?: 'read' | 'write';
  };
  events?: string[];
}
