/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Metaproperties for Git author/committer information.
 */
export interface Committer {
  name: string;
  email: string;
  date?: string;
}
