/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Custom property name and associated value
 */
export interface CustomPropertyValue {
  /**
   * The name of the property
   */
  property_name: string;
  /**
   * The value assigned to the property
   */
  value: string | string[] | null;
}
