/* tslint:disable */
import { App, User } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The [deployment](https://docs.github.com/en/rest/reference/deployments#list-deployments).
 */
export interface Deployment {
  url: string;
  id: number;
  node_id: string;
  sha: string;
  ref: string;
  task: string;
  payload: {
    [k: string]: unknown;
  };
  original_environment: string;
  environment: string;
  transient_environment?: boolean;
  production_environment?: boolean;
  description: string | null;
  creator: User;
  created_at: string;
  updated_at: string;
  statuses_url: string;
  repository_url: string;
  performed_via_github_app?: App | null;
}
