/* tslint:disable */
import { App, User } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The [deployment](https://docs.github.com/en/rest/reference/deployments#list-deployments).
 */
export interface Deployment {
  url: string;
  /**
   * Unique identifier of the deployment
   */
  id: number;
  node_id: string;
  sha: string;
  /**
   * The ref to deploy. This can be a branch, tag, or sha.
   */
  ref: string;
  /**
   * Parameter to specify a task to execute
   */
  task: string;
  payload: {
    [k: string]: unknown;
  };
  original_environment: string;
  /**
   * Name of the target deployment environment.
   */
  environment: string;
  /**
   * Specifies if the given environment will no longer exist at some point in the future. Default: false.
   */
  transient_environment?: boolean;
  /**
   * Specifies if the given environment is one that end-users directly interact with. Default: false.
   */
  production_environment?: boolean;
  description: string | null;
  creator: User;
  created_at: string;
  updated_at: string;
  statuses_url: string;
  repository_url: string;
  performed_via_github_app?: App | null;
}
