/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GitHubOrg {
  login: 'github';
  id: 9919;
  node_id: 'MDEyOk9yZ2FuaXphdGlvbjk5MTk=';
  name?: 'GitHub';
  email?: null;
  avatar_url: 'https://avatars.githubusercontent.com/u/9919?v=4';
  gravatar_id: string;
  url: 'https://api.github.com/users/github';
  html_url: 'https://github.com/github';
  followers_url: 'https://api.github.com/users/github/followers';
  following_url: 'https://api.github.com/users/github/following{/other_user}';
  gists_url: 'https://api.github.com/users/github/gists{/gist_id}';
  starred_url: 'https://api.github.com/users/github/starred{/owner}{/repo}';
  subscriptions_url: 'https://api.github.com/users/github/subscriptions';
  organizations_url: 'https://api.github.com/users/github/orgs';
  repos_url: 'https://api.github.com/users/github/repos';
  events_url: 'https://api.github.com/users/github/events{/privacy}';
  received_events_url: 'https://api.github.com/users/github/received_events';
  type: 'Organization';
  site_admin: boolean;
}
