/* tslint:disable */
import { User } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The GitHub App installation.
 */
export interface Installation {
  /**
   * The ID of the installation.
   */
  id: number;
  account: User;
  /**
   * Describe whether all repositories have been selected or there's a selection involved
   */
  repository_selection: 'all' | 'selected';
  access_tokens_url: string;
  repositories_url: string;
  html_url: string;
  app_id: number;
  app_slug?: string;
  /**
   * The ID of the user or organization this token is being scoped to.
   */
  target_id: number;
  target_type: 'User' | 'Organization';
  permissions: {
    actions?: 'read' | 'write';
    administration?: 'read' | 'write';
    checks?: 'read' | 'write';
    contents?: 'read' | 'write';
    deployments?: 'read' | 'write';
    discussions?: 'read' | 'write';
    issues?: 'read' | 'write';
    organization_administration?: 'read' | 'write';
    pages?: 'read' | 'write';
    packages?: 'read' | 'write';
    pull_requests?: 'read' | 'write';
    repository_hooks?: 'read' | 'write';
    repository_projects?: 'read' | 'write';
    statuses?: 'read' | 'write';
    members?: 'read' | 'write';
    metadata?: 'read' | 'write';
    vulnerability_alerts?: 'read' | 'write';
  };
  events: string[];
  created_at: string | number;
  updated_at: string | number;
  single_file_name: string | null;
  has_multiple_single_files?: boolean;
  single_file_paths?: string[];
  suspended_by?: string | null;
  suspended_at?: string | null;
}
