/* tslint:disable */
import { User } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The membership between the user and the organization. Not present when the action is `member_invited`.
 */
export interface Membership {
  url: string;
  state: string;
  role: string;
  organization_url: string;
  user: User;
}
