/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PackageNPMMetadata {
  name?: string;
  version?: string;
  npm_user?: string;
  author?: {
    [k: string]: string;
  } | null;
  bugs?: {
    [k: string]: string;
  } | null;
  dependencies?: {
    [k: string]: string;
  };
  dev_dependencies?: {
    [k: string]: string;
  };
  peer_dependencies?: {
    [k: string]: string;
  };
  optional_dependencies?: {
    [k: string]: string;
  };
  description?: string;
  dist?: {
    [k: string]: string;
  } | null;
  git_head?: string;
  homepage?: string;
  license?: string;
  main?: string;
  repository?: {
    [k: string]: string;
  } | null;
  scripts?: {
    [k: string]: unknown;
  };
  id?: string;
  node_version?: string;
  npm_version?: string;
  has_shrinkwrap?: boolean;
  maintainers?: {
    [k: string]: unknown;
  }[];
  contributors?: {
    [k: string]: unknown;
  }[];
  engines?: {
    [k: string]: string;
  };
  keywords?: string[];
  files?: string[];
  bin?: {
    [k: string]: unknown;
  };
  man?: {
    [k: string]: unknown;
  };
  directories?: {
    [k: string]: string;
  } | null;
  os?: string[];
  cpu?: string[];
  readme?: string;
  installation_command?: string;
  release_id?: number;
  commit_oid?: string;
  published_via_actions?: boolean;
  deleted_by_id?: number;
}
