/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PackageNugetMetadata {
  id?:
    | string
    | {
        [k: string]: unknown;
      }
    | number;
  name?: string;
  value?:
    | boolean
    | string
    | number
    | {
        url?: string;
        branch?: string;
        commit?: string;
        type?: string;
      };
}
