/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Reactions {
  'url': string;
  'total_count': number;
  '+1': number;
  '-1': number;
  'laugh': number;
  'hooray': number;
  'confused': number;
  'heart': number;
  'rocket': number;
  'eyes': number;
}
