/* tslint:disable */
import { Reactions, ReleaseAsset, User } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The [release](https://docs.github.com/en/rest/reference/repos/#get-a-release) object.
 */
export interface Release {
  url: string;
  assets_url: string;
  upload_url: string;
  html_url: string;
  id: number;
  node_id: string;
  /**
   * The name of the tag.
   */
  tag_name: string;
  /**
   * Specifies the commitish value that determines where the Git tag is created from.
   */
  target_commitish: string;
  name: string;
  /**
   * Wether the release is a draft or published
   */
  draft: boolean;
  author: User;
  /**
   * Whether the release is identified as a prerelease or a full release.
   */
  prerelease: boolean;
  created_at: string | null;
  published_at: string | null;
  assets: ReleaseAsset[];
  tarball_url: string | null;
  zipball_url: string | null;
  body: string;
  reactions?: Reactions;
  discussion_url?: string;
}
