/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A CWE weakness assigned to the advisory.
 */
export interface SecurityAdvisoryCwes {
  /**
   * The unique CWE ID.
   */
  cwe_id: string;
  /**
   * The short, plain text name of the CWE.
   */
  name: string;
}
