/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WebhookEvents =
  | (
      | 'branch_protection_rule'
      | 'check_run'
      | 'check_suite'
      | 'code_scanning_alert'
      | 'commit_comment'
      | 'create'
      | 'delete'
      | 'deployment'
      | 'deployment_status'
      | 'deploy_key'
      | 'discussion'
      | 'discussion_comment'
      | 'fork'
      | 'gollum'
      | 'issues'
      | 'issue_comment'
      | 'label'
      | 'member'
      | 'membership'
      | 'meta'
      | 'milestone'
      | 'organization'
      | 'org_block'
      | 'package'
      | 'page_build'
      | 'project'
      | 'project_card'
      | 'project_column'
      | 'public'
      | 'pull_request'
      | 'pull_request_review'
      | 'pull_request_review_comment'
      | 'pull_request_review_thread'
      | 'push'
      | 'registry_package'
      | 'release'
      | 'repository'
      | 'repository_import'
      | 'repository_vulnerability_alert'
      | 'secret_scanning_alert'
      | 'star'
      | 'status'
      | 'team'
      | 'team_add'
      | 'watch'
      | 'workflow_job'
      | 'workflow_run'
    )[]
  | ['*'];
