/* tslint:disable */
import { WorkflowStep } from '.';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WorkflowJob {
  id: number;
  run_id: number;
  head_sha: string;
  node_id: string;
  name: string;
  check_run_url: string;
  run_url: string;
  html_url: string;
  url: string;
  status: 'queued' | 'in_progress' | 'completed';
  steps: [WorkflowStep, ...WorkflowStep[]];
  conclusion: 'success' | 'failure' | null;
  labels: string[];
  started_at: string;
  completed_at: string | null;
}
