/* tslint:disable */
import {
  CustomPropertyValue,
  InstallationLite,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CustomPropertyValuesUpdatedEvent {
  action: 'updated';
  installation?: InstallationLite;
  repository: Repository;
  organization: Organization;
  sender: User;
  /**
   * The new custom property values for the repository.
   */
  new_property_values: CustomPropertyValue[];
  /**
   * The old custom property values for the repository.
   */
  old_property_values: CustomPropertyValue[];
}
