/* tslint:disable */
import {
  InstallationLite,
  Organization,
  Repository,
  User,
  WorkflowJob,
  WorkflowStepInProgress
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WorkflowJobInProgressEvent {
  action: 'in_progress';
  organization?: Organization;
  installation?: InstallationLite;
  repository: Repository;
  sender: User;
  workflow_job: WorkflowJob & {
    status: 'in_progress';
    steps: [WorkflowStepInProgress, ...WorkflowStepInProgress[]];
  };
}
