/* tslint:disable */
import { InstallationLite, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user forks a repository.
 */
export interface ForkEvent {
  /**
   * The created [`repository`](https://docs.github.com/en/rest/reference/repos#get-a-repository) resource.
   */
  forkee: Repository & {
    fork?: true;
  };
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
