/* tslint:disable */
import { Installation, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MemberEditedEvent {
  action: 'edited';
  member: User;
  changes: {
    old_permission: {
      from: string;
    };
  };
  repository: Repository;
  installation?: Installation;
  sender: User;
}
