/* tslint:disable */
import { Installation, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MemberRemovedEvent {
  action: 'removed';
  member: User;
  repository: Repository;
  installation?: Installation;
  sender: User;
}
