/* tslint:disable */
import { Repository, User, WebhookEvents } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface MetaDeletedEvent {
  action: 'deleted';
  /**
   * The id of the modified webhook.
   */
  hook_id: number;
  /**
   * The modified webhook. This will contain different keys based on the type of webhook it is: repository, organization, business, app, or GitHub Marketplace.
   */
  hook: {
    type: string;
    id: number;
    name: string;
    active: boolean;
    events: WebhookEvents;
    /**
     * Configuration object of the webhook
     */
    config: {
      /**
       * The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.
       */
      content_type: 'json' | 'form';
      /**
       * If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value for [delivery signature headers](https://docs.github.com/webhooks/event-payloads/#delivery-headers).
       */
      secret?: string;
      /**
       * The URL to which the payloads will be delivered.
       */
      url: string;
      /**
       * Determines whether the SSL certificate of the host for `url` will be verified when delivering payloads. Supported values include `0` (verification is performed) and `1` (verification is not performed). The default is `0`.
       */
      insecure_ssl: '0' | '1';
    };
    updated_at: string;
    created_at: string;
  };
  repository: Repository;
  sender: User;
}
