/* tslint:disable */
import {
  Deployment,
  InstallationLite,
  Organization,
  PullRequest,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DeploymentProtectionRuleRequestedEvent {
  action: 'requested';
  /**
   * The name of the environment that has the deployment protection rule.
   */
  environment?: string;
  /**
   * The event that triggered the deployment protection rule.
   */
  event?: string;
  /**
   * The URL to review the deployment protection rule.
   */
  deployment_callback_url?: string;
  deployment?: Deployment;
  pull_requests?: PullRequest[];
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
