/* tslint:disable */
import { InstallationLite, Organization, Repository, User } from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WorkflowDispatchEvent {
  /**
   * Inputs to the workflow. Each key represents the name of the input while it's value represents the value of that input.
   */
  inputs: {
    [k: string]: unknown;
  } | null;
  /**
   * The branch ref from which the workflow was run.
   */
  ref: string;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
  /**
   * Relative path to the workflow file which contains the workflow.
   */
  workflow: string;
}
