/* tslint:disable */
import {
  InstallationLite,
  Issue,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Activity related to an issue. The type of activity is specified in the action property.
 */
export interface IssuesAssignedEvent {
  /**
   * The action that was performed.
   */
  action: 'assigned';
  issue: Issue;
  /**
   * The optional user who was assigned or unassigned from the issue.
   */
  assignee?: User | null;
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
