/* tslint:disable */
import {
  InstallationLite,
  Issue,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IssuesClosedEvent {
  /**
   * The action that was performed.
   */
  action: 'closed';
  /**
   * The [issue](https://docs.github.com/en/rest/reference/issues) itself.
   */
  issue: Issue & {
    state: 'closed';
    closed_at: string;
  };
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
