/* tslint:disable */
import {
  InstallationLite,
  Issue,
  Organization,
  Repository,
  User
} from '../common';
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface IssuesLockedEvent {
  action: 'locked';
  issue: Issue & {
    locked: true;
    active_lock_reason: 'resolved' | 'off-topic' | 'too heated' | 'spam' | null;
  };
  repository: Repository;
  sender: User;
  installation?: InstallationLite;
  organization?: Organization;
}
